//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_MATERIAS
    {
        public CAT_MATERIAS()
        {
            this.MATERIAS = new HashSet<MATERIAS>();
        }
    
        public int IdMateriaCat { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<decimal> Costo { get; set; }
    
        public virtual ICollection<MATERIAS> MATERIAS { get; set; }
    }
}
