//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAS
    {
        public int IdMateria { get; set; }
        public Nullable<int> IdAlumno { get; set; }
        public Nullable<int> IdMateriaCat { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ALUMNOS ALUMNOS { get; set; }
        public virtual CAT_MATERIAS CAT_MATERIAS { get; set; }
    }
}
